name: Build Image Workflow
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'


      - name: build docker image
        run: ./mvnw spring-boot:build-image -DskipTests